### ISSUE TITLE
Can't parse Int64

### ISSUE THREAD

**Issue by R0binBl00d** [CrOrc/Cr.ArgParse#1]
Hi, nice Lib. Busy trying to use this but I'm failing to parse Int64, already tried 
Argument Type = typeof(Int64), TypeName = "long", ...
tried to debug but couldn't exactly find the conversion.
Would be great if you could give me a hint how to solve this.
The parser always changes the numbers to string and all tests fail 
(well, they don't show up and VS says something failed :-)

**Comment by CrOrc** [comment]
You can add support for int64 to https://github.com/CrOrc/Cr.ArgParse/blob/90c0af3f2dac8939149aca5dd2ba6e1b7f376fc5/src/Cr.ArgParse/ActionContainer.cs#L36-L44

**Comment by R0binBl00d** [comment]
Hi, up and running, thx.
